//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_UI_CanvasScaler_ScaleModeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.UI.CanvasScaler.ScaleMode));
		L.RegVar("ConstantPixelSize", get_ConstantPixelSize, null);
		L.RegVar("ScaleWithScreenSize", get_ScaleWithScreenSize, null);
		L.RegVar("ConstantPhysicalSize", get_ConstantPhysicalSize, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ConstantPixelSize(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.CanvasScaler.ScaleMode.ConstantPixelSize);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ScaleWithScreenSize(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.CanvasScaler.ScaleMode.ScaleWithScreenSize);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ConstantPhysicalSize(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.CanvasScaler.ScaleMode.ConstantPhysicalSize);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.UI.CanvasScaler.ScaleMode o = (UnityEngine.UI.CanvasScaler.ScaleMode)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

