//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_EventSystems_TouchInputModuleWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UnityEngine.EventSystems.TouchInputModule), typeof(UnityEngine.EventSystems.PointerInputModule));
		L.RegFunction("UpdateModule", UpdateModule);
		L.RegFunction("IsModuleSupported", IsModuleSupported);
		L.RegFunction("ShouldActivateModule", ShouldActivateModule);
		L.RegFunction("Process", Process);
		L.RegFunction("DeactivateModule", DeactivateModule);
		L.RegFunction("ToString", ToString);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("forceModuleActive", get_forceModuleActive, set_forceModuleActive);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UpdateModule(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.EventSystems.TouchInputModule obj = (UnityEngine.EventSystems.TouchInputModule)ToLua.CheckObject(L, 1, typeof(UnityEngine.EventSystems.TouchInputModule));
			obj.UpdateModule();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsModuleSupported(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.EventSystems.TouchInputModule obj = (UnityEngine.EventSystems.TouchInputModule)ToLua.CheckObject(L, 1, typeof(UnityEngine.EventSystems.TouchInputModule));
			bool o = obj.IsModuleSupported();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShouldActivateModule(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.EventSystems.TouchInputModule obj = (UnityEngine.EventSystems.TouchInputModule)ToLua.CheckObject(L, 1, typeof(UnityEngine.EventSystems.TouchInputModule));
			bool o = obj.ShouldActivateModule();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Process(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.EventSystems.TouchInputModule obj = (UnityEngine.EventSystems.TouchInputModule)ToLua.CheckObject(L, 1, typeof(UnityEngine.EventSystems.TouchInputModule));
			obj.Process();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DeactivateModule(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.EventSystems.TouchInputModule obj = (UnityEngine.EventSystems.TouchInputModule)ToLua.CheckObject(L, 1, typeof(UnityEngine.EventSystems.TouchInputModule));
			obj.DeactivateModule();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ToString(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.EventSystems.TouchInputModule obj = (UnityEngine.EventSystems.TouchInputModule)ToLua.CheckObject(L, 1, typeof(UnityEngine.EventSystems.TouchInputModule));
			string o = obj.ToString();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_forceModuleActive(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.EventSystems.TouchInputModule obj = (UnityEngine.EventSystems.TouchInputModule)o;
			bool ret = obj.forceModuleActive;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index forceModuleActive on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_forceModuleActive(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.EventSystems.TouchInputModule obj = (UnityEngine.EventSystems.TouchInputModule)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.forceModuleActive = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index forceModuleActive on a nil value" : e.Message);
		}
	}
}

